# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZJT2QwvV3SIIzh3RkJ4NH3moiggouZky
"""

import streamlit as st
st.write("""
# Largest among 3 numbers

This app gives the largest number among 3 provided inputs
""")
#Get Input

st.header('User Input Numbers')

a = st.number_input('Insert first number',key=1)

b = st.number_input('Insert second number',key=2)

c = st.number_input('Insert third number',key=3)

def maximum(a,b,c):
  if (a >= b) and (a >= c):
    largest = a
  elif (b >= a) and (b >= c):
    largest = b
  else:
    largest = c
  return largest

st.write('The answer is ', maximum(a,b,c))
